-- user
insert into user(email, password, username, phone, enabled) value ("admin@gmail.com", "admin", "I am admin", 0123456789, true);
insert into user(email, password, username, phone, enabled) value ("user@gmail.com", "user", "I am user", 0011235813, true);
insert into user(email, password, username, phone, enabled) value ("guest@gmail.com", "guest", "I am guest", 0808080808, true);

-- book
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("book", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("angular", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("spring", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("docker", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("haizzz", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("nobody who care", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("I want to relax", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("I love myself", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("I say no", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);
insert into book(title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number) value ("I say yes", "ltp", "ltp publisher", "20/07/2022", "Vietnam", "no content type", 1, "no format", "isbn", 1.0, 8.0, 8.8, true, "no description", 10);